### ISSUE TITLE
Fix CI error

### ISSUE THREAD

**Issue by Anonyma** [Zondax/blockatlas#4]
Fix CI error on merged PR: https://github.com/trustwallet/blockatlas/runs/2542687524

**Comment by emmanuelm41** [comment]
It was fixed locally [here](https://github.com/Zondax/blockatlas/pull/6). We are waiting to get approved [here](https://github.com/trustwallet/blockatlas/pull/1451).

**Comment by emmanuelm41** [comment]
The PR was merged, so we can close this issue.
